package com.allyoucanexercise.back_end.exercise;

public enum ExerciseGroup {
    SHOULDERS,CHEST,FOREARMS,OBLIQUES,QUADS,ADDUCTORS,ABS,BICEPS,CARDIO,TRAPS,TRICEPS,ABDUCTORS,HAMSTRINGS,CALVES,LATS,LOWER_BACK,GLUTES
}
