services:
  mysql:
    container_name: 'allyoucanexercise-mysql'
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=exercise-database
      - MYSQL_USER=alisha
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
          #  This pings the MySQL server and returns mysqld is alive if it's healthy. The --silent flag suppresses unnecessary output.
          #  test: ["CMD-SHELL", "mysqladmin ping -ualisha -psecret --silent"]
           test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
           interval: 10s
           timeout: 10s
           retries: 3
    volumes:
      - ./back-end/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./back-end
    # environment:
    #   - MYSQL_DATABASE=exercise-database
    #   - MYSQL_USER=alisha
    #   - MYSQL_PASSWORD=secret
    #   - DB_HOST=mysql
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/exercise-database
      SPRING_DATASOURCE_USERNAME: alisha
      SPRING_DATASOURCE_PASSWORD: secret
    command: ["./wait-for-it.sh", "mysql:3306", "--timeout=60", "--", "java", "-jar", "app.jar"]

  frontend:
    build:
      context: ./front-end
    ports:
      - '3000:80'
    depends_on:
      - backend  # Ensure backend is ready before frontend
    volumes:
      - ./front-end/dist:/usr/share/nginx/html  # Optionally if you want to mount the build directly