services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=exercise-database'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=alisha'
    ports:
      - '3306:3306'
    volumes:
      - ./back-end/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql


