services:
  mysql:
    container_name: 'mysql-prod'
    env_file:
      - .env
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "alisha", "-p$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql  

  backend:
    build:
      context: ./back-end
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "app.jar"]

  frontend:
    build:
      context: ./front-end
    env_file:
      - .env  
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  mysql-data:    
