services:
  mysql:
    container_name: 'mysql-prod'
    env_file:
      - .env
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "app.jar"]

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
