# 🟩 Very lightweight Nginx container to serve static files

# this assumes I have built the build file in vs code and copied over the dist folder into the front-end folder
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY dist /usr/share/nginx/html

COPY public /usr/share/nginx/html/images

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
