import axios from 'axios';
import Cookies from 'js-cookie';

const IMAGES = {
  "Abduction Machine": new URL('./undefined/Abduction Machine.png', import.meta.url).href,
  "Around the World": new URL('./undefined/Around the World.png', import.meta.url).href,
  "Dumbbell Overhead Press": new URL('./undefined/Dumbbell Overhead Press.png', import.meta.url).href,
  "Overhead Press Single Arm": new URL('./undefined/Overhead Press Single Arm.png', import.meta.url).href,
  "Barbell Overhead Press": new URL('./undefined/Barbell Overhead Press.png', import.meta.url).href,
  "Barbell Behind the Neck Press": new URL('./undefined/Barbell Behind the Neck Press.png', import.meta.url).href,
  "Barbell Upright Row": new URL('./undefined/Barbell Upright Row.png', import.meta.url).href,
  "EZ Bar Upright Row": new URL('./undefined/EZ Bar Upright Row.png', import.meta.url).href,
  "Cable Upright Row": new URL('./undefined/Cable Upright Row.png', import.meta.url).href,
  "Dumbbell Upright Row": new URL('./undefined/Dumbbell Upright Row.png', import.meta.url).href,
  "Dumbbell Lateral Raise": new URL('./undefined/Dumbbell Lateral Raise.png', import.meta.url).href,
  "Barbell Front Raise": new URL('./undefined/Barbell Front Raise.png', import.meta.url).href,
  "Dumbbell Front Raise": new URL('./undefined/Dumbbell Front Raise.png', import.meta.url).href,
  "Dumbbell Bent Over Reverse Fly": new URL('./undefined/Dumbbell Bent Over Reverse Fly.png', import.meta.url).href,
  "Dumbbell Incline Prone Reverse Fly": new URL('./undefined/Dumbbell Incline Prone Reverse Fly.png', import.meta.url).href,
  "Cable Face Pull": new URL('./undefined/Cable Face Pull.png', import.meta.url).href,
  "Barbell Bench Press": new URL('./undefined/Barbell Bench Press.png', import.meta.url).href,
  "Barbell Bench Press Close Grip": new URL('./undefined/Barbell Bench Press Close Grip.png', import.meta.url).href,
  "Barbell Bench Press Wide Grip": new URL('./undefined/Barbell Bench Press Wide Grip.png', import.meta.url).href,
  "Dumbbell Bench Press": new URL('./undefined/Dumbbell Bench Press.png', import.meta.url).href,
  "Incline Dumbbell Bench Press": new URL('./undefined/Incline Dumbbell Bench Press.png', import.meta.url).href,
  "Dumbbell Fly": new URL('./undefined/Dumbbell Fly.png', import.meta.url).href,
  "Decline Dumbbell Fly": new URL('./undefined/Decline Dumbbell Fly.png', import.meta.url).href,
  "Medium Cable Fly": new URL('./undefined/Medium Cable Fly.png', import.meta.url).href,
  "High Cable Fly": new URL('./undefined/High Cable Fly.png', import.meta.url).href,
  "Low Cable Fly": new URL('./undefined/Low Cable Fly.png', import.meta.url).href,
  "Chest Press Machine": new URL('./undefined/Chest Press Machine.png', import.meta.url).href,
  "Chest Fly Machine": new URL('./undefined/Chest Fly Machine.png', import.meta.url).href,
  "Push-Up Close Grip": new URL('./undefined/Push-Up Close Grip.png', import.meta.url).href,
  "Dips": new URL('./undefined/Dips.png', import.meta.url).href,
  "Push-Up": new URL('./undefined/Push-Up.png', import.meta.url).href,
  "Standing Dumbbell Wrist Curl": new URL('./undefined/Standing Dumbbell Wrist Curl.png', import.meta.url).href,
  "Behind Back Barbell Wrist Curl": new URL('./undefined/Behind Back Barbell Wrist Curl.png', import.meta.url).href,
  "Preacher Dumbbell Wrist Curl": new URL('./undefined/Preacher Dumbbell Wrist Curl.png', import.meta.url).href,
  "Side Plank": new URL('./undefined/Side Plank.png', import.meta.url).href,
  "Hanging Windshield Wipers": new URL('./undefined/Hanging Windshield Wipers.png', import.meta.url).href,
  "Standing Dumbbell Side Bend": new URL('./undefined/Standing Dumbbell Side Bend.png', import.meta.url).href,
  "Roman Chair Side Bend": new URL('./undefined/Roman Chair Side Bend.png', import.meta.url).href,
  "Barbell Back Squat": new URL('./undefined/Barbell Back Squat.png', import.meta.url).href,
  "Barbell Front Squat": new URL('./undefined/Barbell Front Squat.png', import.meta.url).href,
  "Barbell Lunge": new URL('./undefined/Barbell Lunge.png', import.meta.url).href,
  "Goblet Squat": new URL('./undefined/Goblet Squat.png', import.meta.url).href,
  "Goblet Lunge": new URL('./undefined/Goblet Lunge.png', import.meta.url).href,
  "Goblet Bulgarian Lunge": new URL('./undefined/Goblet Bulgarian Lunge.png', import.meta.url).href,
  "Bodyweight Squat": new URL('./undefined/Bodyweight Squat.png', import.meta.url).href,
  "Dumbbell Lunge": new URL('./undefined/Dumbbell Lunge.png', import.meta.url).href,
  "Dumbbell Walking Lunges": new URL('./undefined/Dumbbell Walking Lunges.png', import.meta.url).href,
  "Dumbbell Step Up": new URL('./undefined/Dumbbell Step Up.png', import.meta.url).href,
  "Step Up": new URL('./undefined/Step Up.png', import.meta.url).href,
  "Leg Press": new URL('./undefined/Leg Press.png', import.meta.url).href,
  "Leg Extension": new URL('./undefined/Leg Extension.png', import.meta.url).href,
  "Bodyweight Lunge": new URL('./undefined/Bodyweight Lunge.png', import.meta.url).href,
  "Bodyweight Bulgarian Lunge": new URL('./undefined/Bodyweight Bulgarian Lunge.png', import.meta.url).href,
  "Run": new URL('./undefined/Run.png', import.meta.url).href,
  "Run on Treadmill": new URL('./undefined/Run on Treadmill.png', import.meta.url).href,
  "Bicycle Machine": new URL('./undefined/Bicycle Machine.png', import.meta.url).href,
  "Cycling": new URL('./undefined/Cycling.png', import.meta.url).href,
  "Elliptical Machine": new URL('./undefined/Elliptical Machine.png', import.meta.url).href,
  "Step Machine": new URL('./undefined/Step Machine.png', import.meta.url).href,
  "Jump Rope": new URL('./undefined/Jump Rope.png', import.meta.url).href,
  "Burpees": new URL('./undefined/Burpees.png', import.meta.url).href,
  "Mountain Climbers": new URL('./undefined/Mountain Climbers.png', import.meta.url).href,
  "Battling Rope": new URL('./undefined/Battling Rope.png', import.meta.url).href,
  "Walk on Treadmill": new URL('./undefined/Walk on Treadmill.png', import.meta.url).href,
  "Walk": new URL('./undefined/Walk.png', import.meta.url).href,
  "Reverse Bicep Curls": new URL('./undefined/Reverse Bicep Curls.png', import.meta.url).href,
  "Bicep Curl to Opposite Shoulder": new URL('./undefined/Bicep Curl to Opposite Shoulder.png', import.meta.url).href,
  "Dumbbell Side Curl": new URL('./undefined/Dumbbell Side Curl.png', import.meta.url).href,
  "Dumbbell Bicep Curl": new URL('./undefined/Dumbbell Bicep Curl.png', import.meta.url).href,
  "Dumbbell Hammer Curl": new URL('./undefined/Dumbbell Hammer Curl.png', import.meta.url).href,
  "Incline Dumbbell Hammer Curl": new URL('./undefined/Incline Dumbbell Hammer Curl.png', import.meta.url).href,
  "Dumbbell Preacher Curl": new URL('./undefined/Dumbbell Preacher Curl.png', import.meta.url).href,
  "Dumbbell Preacher Hammer Curl": new URL('./undefined/Dumbbell Preacher Hammer Curl.png', import.meta.url).href,
  "Incline Dumbbell Bicep Curl": new URL('./undefined/Incline Dumbbell Bicep Curl.png', import.meta.url).href,
  "Crunches": new URL('./undefined/Crunches.png', import.meta.url).href,
  "Situps": new URL('./undefined/Situps.png', import.meta.url).href,
  "Decline Crunches": new URL('./undefined/Decline Crunches.png', import.meta.url).href,
  "V-Ups": new URL('./undefined/V-Ups.png', import.meta.url).href,
  "Leg Raises": new URL('./undefined/Leg Raises.png', import.meta.url).href,
  "Reverse Crunch Up": new URL('./undefined/Reverse Crunch Up.png', import.meta.url).href,
  "Hanging Knee Raise": new URL('./undefined/Hanging Knee Raise.png', import.meta.url).href,
  "Hanging Leg Raise": new URL('./undefined/Hanging Leg Raise.png', import.meta.url).href,
  "Toes to Bar": new URL('./undefined/Toes to Bar.png', import.meta.url).href,
  "Ab Station Knee Raise": new URL('./undefined/Ab Station Knee Raise.png', import.meta.url).href,
  "Ab Station Leg Raise": new URL('./undefined/Ab Station Leg Raise.png', import.meta.url).href,
  "Ab Machine": new URL('./undefined/Ab Machine.png', import.meta.url).href,
  "Decline Situps": new URL('./undefined/Decline Situps.png', import.meta.url).href,
  "Plank": new URL('./undefined/Plank.png', import.meta.url).href,
  "Single Leg Cable Adduction": new URL('./undefined/Single Leg Cable Adduction.png', import.meta.url).href,
  "Adduction Machine": new URL('./undefined/Adduction Machine.png', import.meta.url).href,
  "Russian Twist": new URL('./undefined/Russian Twist.png', import.meta.url).href,
  "Standing Dumbbell Shrugs": new URL('./undefined/Standing Dumbbell Shrugs.png', import.meta.url).href,
  "Dumbbell Skull Crusher": new URL('./undefined/Dumbbell Skull Crusher.png', import.meta.url).href,
  "Single Arm Dumbbell Row": new URL('./undefined/Single Arm Dumbbell Row.png', import.meta.url).href,
  "Superman": new URL('./undefined/Superman.png', import.meta.url).href,
  "Barbell Hip Thrust": new URL('./undefined/Barbell Hip Thrust.png', import.meta.url).href,
  "Barbell Deadlift": new URL('./undefined/Barbell Deadlift.png', import.meta.url).href,
  "Calf Raises": new URL('./undefined/Calf Raises.png', import.meta.url).href,
};

export default IMAGES;
