version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    environment:
      MYSQL_DATABASE: exercise-database
      MYSQL_USER: alisha
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
